import {
    ChevronLeft,
    ChevronRight,
    Menu,
    PanelLeftOpen,
    ChevronsUpDown,
    PanelLeftClose,
    ChevronUp,
    ChevronDown,
    X,
    ClipboardList,
    Trash,
    CirclePlus,
    NotebookPen,
    Cloud,
    QrCode,
    Eye,
    Pencil,
    Check,
    Plus,
    ArrowLeft,
    LayoutGrid,
    Download,
    MessageSquareText,
    Settings,
    ArrowDown,
    Upload,
    Home,
    BriefcaseBusiness,
    Moon,
    Sun,
    ArrowRight,
    Bell,
    BellDot,
    ListPlus,
    Paperclip,
    FilePen,
} from 'lucide-vue-next';

export default {
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    menu: Menu,
    'panel-left-open': PanelLeftOpen,
    'chevrons-up-down': ChevronsUpDown,
    'panel-left-close': PanelLeftClose,
    'chevron-up': ChevronUp,
    'chevron-down': ChevronDown,
    x: X,
    'clipboard-list': ClipboardList,
    trash: Trash,
    'circle-plus': CirclePlus,
    'notebook-pen': NotebookPen,
    cloud: Cloud,
    'qr-code': QrCode,
    eye: Eye,
    pencil: Pencil,
    check: Check,
    plus: Plus,
    'arrow-left': ArrowLeft,
    'layout-grid': LayoutGrid,
    download: Download,
    'message-square-text': MessageSquareText,
    settings: Settings,
    'arrow-down': ArrowDown,
    upload: Upload,
    home: Home,
    'briefcase-business': BriefcaseBusiness,
    moon: Moon,
    sun: Sun,
    'arrow-right': ArrowRight,
    bell: Bell,
    'bell-dot': BellDot,
    'list-plus': ListPlus,
    paperclip: Paperclip,
    'file-pen': FilePen,
};
